index:
    path: /app/v1/
    controller: App\Controller\UsersController::index
    methods: [GET]
weather:
    path: /app/v1/users/{userid}/weather
    controller: App\Controller\UsersController::weather
    methods: [GET]
    requirements:
      customerId: '\d+'

